### ISSUE TITLE
개발 진행도 

### ISSUE THREAD

**Issue by kysloves** [ygnoh/smart-github#14]
# TODO 
## Core functionality 

- [x] 동적으로 이슈 템플릿을 읽어옴  
  - [x] 공개 repo에서 템플릿을 읽어올 수 있다.
  - [x] private repo에서 템플릿을 읽어올 수 있다.
    - [x] 사용자에게 익스텐션을 적용할 hosts 정보 입력 받기
    - [x] 사용자에게 token 입력 받기
      - [x] 토큰 입력 layer 작업
    - [x] token 정보를 통해 템플릿 읽어오기
- [x] 이슈 버튼 마우스 호버시 선택 메뉴 뜸
- [x] PR 버튼 마우스 호버시 선택 메뉴 뜸
- [ ] 사용자로 하여금 이슈 템플릿 
  - [ ] CRUD
  - [ ] (도전과제 @yesoll.kim) 마크다운 프리뷰 
- [x] 스토어 등록
